'use client';

import { useSession } from 'next-auth/react';
import { useState, useEffect, useMemo, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import ElaanImage from '@public/app_logo.png';
import apiService from '@/utils/apiService';
import toast from 'react-hot-toast';

interface ActivityData {
  id?: number;
  user_id: number;
  full_name: string;
  username: string;
  report_date: string;
  daily_office_visits: number;
  client_matured: number;
  daily_lead_follow_up: number;
  lead_assigned: number;
  total_dialed_calls: number;
  total_connected_calls: number;
  total_whatsapp: number;
  dealers_meeting: number;
  dealers_register: number;
  office_activity: string;
}

interface ReportBlock {
  date: string;
  activities: ActivityData[];
}

export default function PrintFullReport({ slug }: { slug: string }) {
  const slug_data: ActivityData = JSON.parse(decodeURIComponent(slug));
  const { from, to }: any = slug_data;
  const { data: session } = useSession();
  const [isClient, setIsClient] = useState(false);
  const [reportData, setReportData] = useState<ReportBlock[]>([]);

  useEffect(() => {
    setIsClient(true);
  }, []);

  const memoizedSession = useMemo(() => session, [session]);

  const fetchData = useCallback(async () => {
    try {
      const response = await apiService.get(`/full-daily-activity-report?from=${from}&to=${to}`);
      const report = response?.data?.data || [];
      setReportData(report);
    } catch (error: any) {
      console.error('Error fetching report:', error);
      toast.error(error?.response?.data?.message || 'Failed to fetch report');
    }
  }, [from, to]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const currentDate = new Date().toLocaleDateString('en-US', {
    weekday: 'short',
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });

  const hasOfficeActivity = (activity?: string) => {
    const value = activity?.trim();
    return Boolean(value && value.toUpperCase() !== 'N/A');
  };

  const hasReportValue = (activity: ActivityData) => (
    Boolean(activity.lead_assigned) ||
    Boolean(activity.total_dialed_calls) ||
    Boolean(activity.total_connected_calls) ||
    Boolean(activity.total_whatsapp) ||
    Boolean(activity.daily_lead_follow_up) ||
    Boolean(activity.daily_office_visits) ||
    Boolean(activity.dealers_meeting) ||
    hasOfficeActivity(activity.office_activity)
  );

  if (!isClient) {
    return <div className="flex justify-center items-center h-screen">Loading...</div>;
  }

  return (
    <div className="print-container">
      <div className="w-full p-4 bg-white rounded-lg shadow-md print:p-0 print:shadow-none print:rounded-none">
        {/* Header */}
        <div className="block md:flex md:justify-between items-center mb-6 print:mb-2">
          <div className="text-center md:text-left">
            <h1 className="text-2xl font-bold text-gray-800 print:text-xl">
              Daily Activity Report
            </h1>
            <div className="mt-2 text-sm text-gray-600 print:text-xs">
              <p>Generated on: {currentDate}</p>
              <p>Generated by: {memoizedSession?.user?.name}</p>
              <p>Date Range: {from} to {to}</p>
            </div>
          </div>
          <div className="w-20 h-20 relative mt-4 md:mt-0 print:w-16 print:h-16">
            <Image
              src={ElaanImage}
              alt="Company Logo"
              fill
              className="object-contain"
              priority
            />
          </div>
        </div>

        {/* Report by Date */}
        {reportData.map(({ date, activities }) => (
          <div key={date} className="mb-4 break-inside-avoid print:mb-2">
            <h2 className="text-lg font-semibold mb-2 print:text-base">
              {new Date(date).toLocaleDateString('en-US', {
                weekday: 'long',
                day: '2-digit',
                month: 'short',
                year: 'numeric',
              })}
            </h2>

            <div className="overflow-x-auto print:overflow-visible">
              {/* SCROLL ON SCREEN, OPEN ON PRINT */}
              <div className="max-h-[60vh] overflow-auto print:max-h-none print:overflow-visible">
                <table className="w-full table-fixed border border-gray-300 text-sm print:text-xs">
                  <thead>
                    <tr>
                      <th className="sticky top-0 z-10 bg-gray-100 px-2 py-1 border-b text-left print:static print:top-auto print:z-auto" style={{ width: '13%' }}>Employee</th>
                      <th className="sticky top-0 z-10 bg-gray-100 px-2 py-1 border-b text-center print:static print:top-auto print:z-auto" style={{ width: '9%' }}>Leads Assigned</th>
                      <th className="sticky top-0 z-10 bg-gray-100 px-2 py-1 border-b text-center print:static print:top-auto print:z-auto" style={{ width: '9%' }}>Total Dialed Calls</th>
                      <th className="sticky top-0 z-10 bg-gray-100 px-2 py-1 border-b text-center print:static print:top-auto print:z-auto" style={{ width: '9%' }}>Total Connected Calls</th>
                      <th className="sticky top-0 z-10 bg-gray-100 px-2 py-1 border-b text-center print:static print:top-auto print:z-auto" style={{ width: '9%' }}>Total WhatsApp</th>
                      <th className="sticky top-0 z-10 bg-gray-100 px-2 py-1 border-b text-center print:static print:top-auto print:z-auto" style={{ width: '9%' }}>Leads Followups</th>
                      <th className="sticky top-0 z-10 bg-gray-100 px-2 py-1 border-b text-center print:static print:top-auto print:z-auto" style={{ width: '9%' }}>Visits / Sites Visited</th>
                      <th className="sticky top-0 z-10 bg-gray-100 px-2 py-1 border-b text-center print:static print:top-auto print:z-auto" style={{ width: '9%' }}>Total Scheduled Meetings</th>
                      {/* Legacy columns hidden from the current activity report UI: Clients Matured, Dealer Registered */}
                      <th className="sticky top-0 z-10 bg-gray-100 px-2 py-1 border-b text-center print:static print:top-auto print:z-auto" style={{ width: '24%' }}>Other Activity</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200">
                    {activities
                      .filter(hasReportValue)
                      .map(a => (
                        <tr key={`${a.user_id}-${date}`} className="break-inside-avoid">
                          <td className="px-2 py-1 border print:border whitespace-nowrap">{a.full_name}</td>
                          <td className="px-2 py-1 text-center border print:border">{a.lead_assigned}</td>
                          <td className="px-2 py-1 text-center border print:border">{a.total_dialed_calls}</td>
                          <td className="px-2 py-1 text-center border print:border">{a.total_connected_calls}</td>
                          <td className="px-2 py-1 text-center border print:border">{a.total_whatsapp}</td>
                          <td className="px-2 py-1 text-center border print:border">{a.daily_lead_follow_up}</td>
                          <td className="px-2 py-1 text-center border print:border">{a.daily_office_visits}</td>
                          <td className="px-2 py-1 text-center border print:border">{a.dealers_meeting}</td>
                          <td className="px-2 py-1 text-center border print:border">{hasOfficeActivity(a.office_activity) ? a.office_activity : 'N/A'}</td>
                        </tr>
                      ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        ))}

        {/* Footer Note */}
        <div className="mt-6 print:mt-4">
          <h3 className="text-gray-500 text-sm font-medium print:text-sm">Note:</h3>
          <p className="text-gray-500 text-xs print:text-xs">
            This report is system generated. No signature required.
          </p>
        </div>

        {/* Print Button */}
        <div className="mt-6 flex justify-end print:hidden">
          <button
            onClick={() => window.print()}
            className="px-6 py-2 bg-black text-white rounded hover:bg-gray-800 transition-colors text-sm"
          >
            Print Report
          </button>
        </div>
      </div>

      {/* Print-specific styles */}
      <style jsx global>{`
        @media print {
          html, body {
            margin: 0 !important;
            padding: 0 !important;
            height: auto !important;
            overflow: visible !important;
            background: white !important;
          }

          * {
            box-sizing: border-box;
            margin: 0 !important;
            padding: 0 !important;
            line-height: 1.2 !important;
          }

          .print-container {
            width: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
          }

          @page {
            size: A4 portrait;
            margin: 10mm;
          }

          table, thead, tbody, tr, td, th {
            break-inside: avoid !important;
            page-break-inside: avoid !important;
          }

          thead {
            display: table-header-group;
          }

          tr {
            page-break-inside: avoid;
          }

          .break-inside-avoid {
            break-inside: avoid;
            page-break-inside: avoid;
          }
        }
      `}</style>
    </div>
  );
}
