'use client';

import { useSession } from 'next-auth/react';
import { useState, useEffect, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import ElaanImage from '@public/app_logo.png';

interface ActivityData {
  id: number;
  daily_office_visits: number;
  client_matured: number;
  daily_lead_follow_up: number;
  lead_assigned: number;
  dealers_meeting: number;
  dealers_register: number;
  office_activity: string;
  full_name: string;
  user: string;
  del: string;
}

export default function SingleReport({ slug }: { slug: string }) {
  const { data: session } = useSession();
  const { back } = useRouter();
  const [isClient, setIsClient] = useState(false);
  const memoizedSession = useMemo(() => session, [session]);

  useEffect(() => {
    setIsClient(true);
  }, []);

  // Parse the slug data
  const slug_data: ActivityData = JSON.parse(decodeURIComponent(slug));
  
  // Get current date
  const currentDate = new Date();
  const formattedDate = currentDate.toLocaleDateString('en-US', {
    weekday: 'short',
    day: '2-digit',
    month: 'short',
    year: 'numeric'
  });

  if (!isClient) {
    return <div className="flex justify-center items-center h-screen">Loading...</div>;
  }

  return (
    <div className="print-container">
      {/* Main Content */}
      <div className="w-full p-4 sm:p-8 lg:p-12 bg-white rounded-lg shadow-md print:shadow-none print:max-w-full print:p-0 print:rounded-none">
        {/* Header Section */}
        <div className="flex flex-col md:flex-row justify-between items-center mb-6 gap-4 print:flex-row print:items-start print:mb-4">
          <div className="order-2 md:order-1 text-center md:text-left print:text-left print:order-1">
            <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold text-gray-800 print:text-2xl">
              Daily Activity Report - {slug_data.full_name}
            </h1>
            <div className="mt-2 text-xs sm:text-sm lg:text-base text-gray-600 space-y-1 print:text-sm print:mt-1">
              <p>Generated on: {formattedDate}</p>
              <p>Generated by: {memoizedSession?.user?.name}</p>
            </div>
          </div>
          <div className="order-1 md:order-2 w-16 h-16 sm:w-20 sm:h-20 md:w-24 md:h-24 relative print:w-20 print:h-20">
            <Image 
              src={ElaanImage}
              alt="Company Logo"
              fill
              className="object-contain"
              priority
            />
          </div>
        </div>

        {/* Activity Table */}
        <div className="overflow-x-auto print:overflow-visible">
          <table className="w-full bg-white border border-gray-200 print:w-full print:border print:border-gray-300">
            <thead>
              <tr className="bg-gray-100 print:bg-gray-100">
                <th colSpan={2} className="py-3 px-4 border-b text-base font-semibold text-gray-700 print:py-2 print:text-base text-center">
                  Daily Activities
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200 print:divide-gray-300">
              <TableRow label="Office Visits" value={slug_data.daily_office_visits} />
              <TableRow label="Clients Matured" value={slug_data.client_matured} />
              <TableRow label="Leads Followups" value={slug_data.daily_lead_follow_up} />
              <TableRow label="Current Leads Assigned" value={slug_data.lead_assigned} />
              <TableRow label="Dealers Meetings" value={slug_data.dealers_meeting} />
              <TableRow label="Dealers Registered" value={slug_data.dealers_register} />
              <TableRow label="Other Office Activity" value={slug_data.office_activity} />
            </tbody>
          </table>
        </div>

        {/* Footer Note */}
        <div className="mt-6 pl-0 md:pl-4 print:mt-4 print:pl-2">
          <h3 className='text-gray-500 text-sm sm:text-base lg:text-lg font-medium print:text-base'>Note:</h3>
          <p className='text-gray-500 text-xs sm:text-sm lg:text-base print:text-sm'>
            This report is system generated, no signature required.
          </p>
        </div>

        {/* Print Button - Moved to right with black background */}
        <div className="mt-6 flex justify-end print:hidden">
          <button
            onClick={() => window.print()}
            className="px-6 py-2 bg-black text-white rounded-lg hover:bg-gray-800 transition-colors text-sm sm:text-base"
          >
            Print Report
          </button>
        </div>
      </div>

      {/* Print-specific styles */}
      <style jsx global>{`
        @media print {
          body {
            background: white !important;
            color: black !important;
            font-size: 12pt;
          }
          .print-container {
            width: 100%;
            margin: 0;
            padding: 0;
          }
          @page {
            size: auto;
            margin: 10mm;
          }
          table {
            page-break-inside: avoid;
          }
          thead {
            display: table-header-group;
          }
          tr {
            page-break-inside: avoid;
          }
        }
      `}</style>
    </div>
  );
}

// Reusable component for table rows with adjusted spacing
function TableRow({ label, value }: { label: string; value: string | number }) {
  return (
    <tr className="hover:bg-gray-50 print:hover:bg-transparent">
      <td className="py-3 px-4 w-1/3 sm:w-2/5 text-sm font-medium text-gray-700 print:py-2 print:px-3 print:text-base print:border print:border-gray-300">
        {label}
      </td>
      <td className="py-3 px-4 w-2/3 sm:w-3/5 text-sm text-gray-600 text-right print:py-2 print:px-3 print:text-base print:border print:border-gray-300">
        {value}
      </td>
    </tr>
  );
}