export const routes = {
  eCommerce: {
    dashboard: '/ecommerce',
    products: '/ecommerce/products',
    createProduct: '/ecommerce/products/create',
    productDetails: (slug: string) => `/ecommerce/products/${slug}`,
    ediProduct: (slug: string) => `/ecommerce/products/${slug}/edit`,
    categories: '/ecommerce/categories',
    createCategory: '/ecommerce/categories/create',
    editCategory: (id: string) => `/ecommerce/categories/${id}/edit`,
    orders: '/ecommerce/orders',
    createOrder: '/ecommerce/orders/create',
    orderDetails: (id: string) => `/ecommerce/orders/${id}`,
    editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
    reviews: '/ecommerce/reviews',
    shop: '/ecommerce/shop',
    cart: '/ecommerce/cart',    
    checkout: '/ecommerce/checkout',
    trackingId: (id: string) => `/ecommerce/tracking/${id}`,
  },
  employee:{
       dashboard:'/employee',
       employeelist:'/employee/list',
       newemployee:'/employee/new',
       zones:'/employee/zones',
       teams:'/employee/teams',
       deleteemployee:'/employee/delete',
       edit: (id: string) => `/employee/${id}/edit`,
       editteam: (id: string) => `/employee/teams/${id}/edit`,
       editzone:(id: string) => `/employee/zones/${id}/edit`,
       //zoneTeams:(id: string) => `/employee/teams/${id}/zones`,
       zoneTeams:(id: string) => `/employee/zones/${id}/teams`,
       members:(id: string) => `/employee/teams/${id}/members`,
       
       details: (id: string) => `/employee/${id}`,
       
  },
  leads:{
    dashboard:'/leads',
    management:'/leads/management',
    new_lead:'/leads/new-lead',
    highly_interested:'/leads/highly_interested',
    // need_to_convince:'/leads/need_to_convince',
    team_member: (id: string) => `/leads/management/${id}`,
    edit: (id: string) => `/leads/${id}/edit`,
    show_label: (id: string) => `/leads/labels/${id}`,
    show_specific_label: (id: string, id1: string) => `/leads/labels/${id}/${id1}`,

    customers:'/leads/customers',
    editCustomer: (id: string) => `/leads/customers/${id}/edit`,
    viewCustomer: (id: string) => `/leads/customers/${id}/view`,
    newcustomer:'/leads/customers/new-customer',
    
    
  },
  project: {
      projectlist: '/project/list',
      newproject:'/project/new',
      editProject: (id: string) => `/project/edit/${id}`,
  },
  searchAndFilter: {
    realEstate: '/search/real-estate',
    nft: '/search/nft',
    flight: '/search/flight',
  },
  support: {
    dashboard: '/support',
    inbox: '/support/inbox',
    supportCategory: (category: string) => `/support/inbox/${category}`,
    messageDetails: (id: string) => `/support/inbox/${id}`,
    snippets: '/support/snippets',
    createSnippet: '/support/snippets/create',
    viewSnippet: (id: string) => `/support/snippets/${id}`,
    editSnippet: (id: string) => `/support/snippets/${id}/edit`,
    templates: '/support/templates',
    createTemplate: '/support/templates/create',
    viewTemplate: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
  
    activitylogs:'/activitylogs'
  ,
  logistics: {
    dashboard: '/logistics',
    shipmentList: '/logistics/shipments',
    customerProfile: '/logistics/customer-profile',
    createShipment: '/logistics/shipments/create',
    // editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
    // shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
    // tracking: (id: string) => `/logistics/tracking/${id}`,
    tracking: (id: string) => `logistics/Activitylogs`,
  },
  executive: {
    dashboard: '/executive',
  },
  analytics: '/analytics',
  financial: {
    dashboard: '/financial',
  },
  file: {
    dashboard: '/file',
    manager: '/file-manager',
    upload: '/file-manager/upload',
    create: '/file-manager/create',
  },
  pos: {
    index: '/point-of-sale',
  },
  eventCalendar: '/event-calendar',
  rolesPermissions: '/roles-permissions',
  invoice: {
    home: '/invoice',
    create: '/invoice/create',
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
  },
  widgets: {
    cards: '/widgets/cards',
    icons: '/widgets/icons',
    charts: '/widgets/charts',
    maps: '/widgets/maps',
    banners: '/widgets/banners',
  },
  tables: {
    basic: '/tables/basic',
    collapsible: '/tables/collapsible',
    enhanced: '/tables/enhanced',
    pagination: '/tables/pagination',
    search: '/tables/search',
    stickyHeader: '/tables/sticky-header',
  },
  multiStep: '/multi-step',
  forms: {
    profileSettings: '/forms/profile-settings',
    activitylogs: '/forms/profile-settings/logs',
    notificationPreference: '/forms/profile-settings/notification',
    personalInformation: '/forms/profile-settings/profile',
    newsletter: '/forms/newsletter',
  },
  emailTemplates: '/email-templates',
  profile: '/profile',
  welcome: '/welcome',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    signUp1: '/auth/signup',
    onboarding: '/auth/onboarding',
    signUp2: '/auth/sign-up-2',
    signUp3: '/auth/sign-up-3',
    signUp4: '/auth/sign-up-4',
    signUp5: '/auth/sign-up-5',
    // sign in
    signIn1: '/signin',
    signIn2: '/auth/sign-in-2',
    signIn3: '/auth/sign-in-3',
    signIn4: '/auth/sign-in-4',
    signIn5: '/auth/sign-in-5',
    // forgot password
    forgotPassword1: '/auth/forgot-password-1',
    forgotPassword2: '/auth/forgot-password-2',
    forgotPassword3: '/auth/forgot-password-3',
    forgotPassword4: '/auth/forgot-password-4',
    forgotPassword5: '/auth/forgot-password-5',
    // OTP
    otp1: '/auth/otp-1',
    otp2: '/auth/otp-2',
    otp3: '/auth/otp-3',
    otp4: '/auth/otp-4',
    otp5: '/auth/otp-5',
  },
  signIn: '/signin',
  onboarding:'/onboarding'
};
