// columns/businessProfilesColumns.tsx
'use client';
import React, { useMemo } from 'react';
import Link from 'next/link';
import { HeaderCell } from '@/components/ui/table';
import { Text } from '@/components/ui/text';
import { Tooltip } from '@/components/ui/tooltip';
import { ActionIcon } from '@/components/ui/action-icon';
import EyeIcon from '@/components/icons/eye';
import { LiaEditSolid } from 'react-icons/lia';
import DeletePopover from '@/app/shared/delete-popover1';
import { useSession } from 'next-auth/react';
import { routes } from '@/config/routes';
import apiService from '@/utils/apiService';
import toast from 'react-hot-toast';
import { BiSolidCertification } from "react-icons/bi";

type ColumnsProps = {
  data: any[];
  sortConfig?: any;
  handleSelectAll: any;
  checkedItems: string[];
  onDeleteItem: (id: string) => void;
  onHeaderCellClick: (value: string) => void;
  onChecked?: (id: string) => void;
};

export const useBusinessProfilesColumns = ({
  data,
  sortConfig,
  checkedItems,
  onDeleteItem,
  onHeaderCellClick,
  handleSelectAll,
  onChecked,
}: ColumnsProps) => {
  
  const { data: session } = useSession();
  const memoizedSession = useMemo(() => session, [session]);
  
const isAdmin = (memoizedSession?.user?.permission ?? 0) >= 9;

  const columns = [
    {
      title: (
        <HeaderCell
          title="ID"
          sortable
          ascending={sortConfig?.direction === 'asc' && sortConfig?.key === 'id'}
        />
      ),
      onHeaderCell: () => onHeaderCellClick('id'),
      dataIndex: 'id',
      key: 'id',
      width: 70,
      render: (value: string | undefined) => (
        <Text className="font-medium text-gray-700 dark:text-gray-600">{value || '—'}</Text>
      ),
    },
    {
      title: (
        <HeaderCell
          title="Full Name"
          sortable
          ascending={sortConfig?.direction === 'asc' && sortConfig?.key === 'full_name'}
        />
      ),
      onHeaderCell: () => onHeaderCellClick('full_name'),
      dataIndex: 'full_name',
      key: 'full_name',
      width: 220,
      render: (v: string | undefined) => (
        <Text className="font-medium text-gray-700 dark:text-gray-600">{v || '—'}</Text>
      ),
    },
    {
      title: (
        <HeaderCell
          title="CNIC"
          sortable
          ascending={sortConfig?.direction === 'asc' && sortConfig?.key === 'cnic'}
        />
      ),
      onHeaderCell: () => onHeaderCellClick('cnic'),
      dataIndex: 'cnic',
      key: 'cnic',
      width: 160,
      render: (v: string | undefined) => (
        <Text className="font-medium text-gray-700 dark:text-gray-600">{v || '—'}</Text>
      ),
    },
    {
      title: (
        <HeaderCell
          title="Mobile"
          sortable
          ascending={sortConfig?.direction === 'asc' && sortConfig?.key === 'mobile'}
        />
      ),
      onHeaderCell: () => onHeaderCellClick('mobile'),
      dataIndex: 'mobile',
      key: 'mobile',
      width: 150,
      render: (v: string | undefined) => (
        <Text className="font-medium text-gray-700 dark:text-gray-600">{v || '—'}</Text>
      ),
    },
    {
      title: (
        <HeaderCell
          title="Email"
          sortable
          ascending={sortConfig?.direction === 'asc' && sortConfig?.key === 'email'}
        />
      ),
      onHeaderCell: () => onHeaderCellClick('email'),
      dataIndex: 'email',
      key: 'email',
      width: 220,
      render: (v: string | undefined) => (
        <Text className="font-medium text-gray-700 dark:text-gray-600">{v || '—'}</Text>
      ),
    },
    // {
    //   title: (
    //     <HeaderCell
    //       title="City"
    //       sortable
    //       ascending={sortConfig?.direction === 'asc' && sortConfig?.key === 'city'}
    //     />
    //   ),
    //   onHeaderCell: () => onHeaderCellClick('city'),
    //   dataIndex: 'city',
    //   key: 'city',
    //   width: 140,
    //   render: (v: string | undefined) => (
    //     <Text className="font-medium text-gray-700 dark:text-gray-600">{v || '—'}</Text>
    //   ),
    // },
    {
      title: (
        <HeaderCell
          title="Generated By"
          sortable
          ascending={sortConfig?.direction === 'asc' && sortConfig?.key === 'user'}
        />
      ),
      onHeaderCell: () => onHeaderCellClick('user'),
      dataIndex: 'user',
      key: 'user',
      width: 220,
      render: (v: string | undefined) => (
        <Text className="font-medium text-gray-700 dark:text-gray-600">{v || '—'}</Text>
      ),
    },
    
    {
      title: (
        <HeaderCell
          title="Filer Status"
          sortable
          ascending={sortConfig?.direction === 'asc' && sortConfig?.key === 'filer_status'}
        />
      ),
      onHeaderCell: () => onHeaderCellClick('filer_status'),
      dataIndex: 'filer_status',
      key: 'filer_status',
      width: 140,
      render: (v: string | undefined) => (
        <div className="font-medium text-gray-700 dark:text-gray-600">
          {v === 'Active Filer' ? (
            <span className="px-2 py-1 rounded bg-green-500 text-white">Active Filer</span>
          ) : v === 'Non-Filer' ? (
            <span className="px-2 py-1 rounded bg-red-500 text-white">Non-Filer</span>
          ) : (
            <span className="px-2 py-1 rounded bg-gray-400 text-white">—</span>
          )}
        </div>
      ),
    },
    {
    title: (
      <HeaderCell
        title="Status"
        sortable
        ascending={sortConfig?.direction === 'asc' && sortConfig?.key === 'status'}
      />
    ),
    onHeaderCell: () => onHeaderCellClick('status'),
    dataIndex: 'status',
    key: 'status',
    width: 200,
    // NOTE: give render access to row so we can call approve for that id
    render: (v: 'N' | 'Y' | undefined, row: any) => {
      if (v === 'N') {
        // NOT admin => show "Click approve"
        if (isAdmin) {
          return (
            <button
              className="px-2 py-1 rounded bg-red-500 text-white"
              onClick={async () => {
                try {
                 const res= await apiService.put(`/business-profiles/${row.id}`,{ status: 'Y' });
                  if (res?.data?.success) {
                    toast.success('Realtor approved successfully');
                  }
                  // optional: toast + refresh logic here
                  // e.g., router.refresh() if using Next 13+ app router
                } catch (err) {
                  toast.error('Failed to approve realtor');
                  console.error('Approve failed', err);
                }
              }}
            >
              Click approve
            </button>
          );
        }
        // Admin sees "In Pending"
        return <span className="px-2 py-1 rounded bg-red-500 text-white">In Pending</span>;
      }

      if (v === 'Y') {
        return <span className="px-2 py-1 rounded bg-green-500 text-white">Active</span>;
      }

      return <span className="px-2 py-1 rounded bg-gray-400 text-white">—</span>;
    },
  },

  {
    title: <HeaderCell title="Action" />,
    dataIndex: 'action',
    key: 'action',
    width: 200,
    render: (_: string, row: any) => {
      return (
        <div className="flex items-center justify-start gap-3 pe-3">
          
          {/* keep Edit as you prefer; if you want admin-only, wrap with isAdmin too */}
          {/* Example: make Edit admin-only */}
  
            <Tooltip size="sm" content={() => 'Edit Details'} placement="top" color="invert">
              <Link href={routes.realtors.edit(row.id)}>
                <ActionIcon
                  tag="span"
                  size="sm"
                  variant="outline"
                  className="hover:!border-gray-900 hover:text-gray-700"
                >
                  <LiaEditSolid className="h-4 w-4" />
                </ActionIcon>
              </Link>
            </Tooltip>
          {/* View is admin-only */}
          {(isAdmin || row.status === "Y") && (
                      <>
                        <Tooltip size="sm" content={() => 'View Details'} placement="top" color="invert">
                          <Link href={routes.tamplets.PrintRealtorReport(row.id)}>
                            <ActionIcon
                              tag="span"
                              size="sm"
                              variant="outline"
                              className="hover:!border-gray-900 hover:text-gray-700"
                            >
                              <EyeIcon className="h-4 w-4" />
                            </ActionIcon>
                          </Link>
                        </Tooltip>

                        <Tooltip size="sm" content={() => 'Certificate'} placement="top" color="invert">
                          <Link href={routes.tamplets.PrintRealtorCert(row.id)}>
                            <ActionIcon
                              tag="span"
                              size="sm"
                              variant="outline"
                              className="hover:!border-gray-900 hover:text-gray-700"
                            >
                              <BiSolidCertification className="h-4 w-4" />
                            </ActionIcon>
                          </Link>
                        </Tooltip>
                      </>
                    )}


        
        </div>
      );
    },
  },
  ];

  return columns;
};
